version: 2

references:

  workspace_root: &workspace_root
                    ~/filmowy

  container_config: &container_config
    docker:
      - image: circleci/android:api-29
    working_directory: *workspace_root
    environment:
      _JAVA_OPTS: -Xmx3072m

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

jobs:

  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Setup environment
          command: ./gradlew dependencies --no-daemon --stacktrace --console=plain
      - run:
          name: Initial build
          command: ./gradlew build -x test -x lint --no-daemon --stacktrace --console=plain
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
      - save_cache:
          <<: *general_cache_key
          paths:
            - "~/.gradle"

  lint:
    <<: *container_config
    steps:
      - *attach_workspace
      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Run lint
          command: ./gradlew lint --no-daemon --stacktrace --console=plain
      - store_artifacts:
          path: ./app/build/reports/
          destination: lint_reports/app/
      - store_test_results:
          path: ./app/build/reports/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - "./app/build/reports/lint-results.xml"

  test:
    <<: *container_config
    steps:
      - *attach_workspace
      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Run app tests
          command: ./gradlew test jacocoTestReport --no-daemon --stacktrace --console=plain
      - run:
          name: Upload unit code coverage to codecov
          command: bash <(curl -s https://codecov.io/bash) -F app
      - store_artifacts:
          path: ./app/build/reports/
          destination: reports/
      - store_test_results:
          path: ./app/build/test-results
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - "./app/build/jacoco"

  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Decrypt keys
          command: |
            gpg --yes --batch --passphrase=$SERVICES_ENCRYPT_KEY ./app/src/release/google-services.json.gpg
            openssl aes-256-cbc -d -in ./app/key-encrypted.p12 -k $ENCRYPT_KEY >> ./app/key.p12
            openssl aes-256-cbc -d -in ./app/upload-key-encrypted.jks -k $ENCRYPT_KEY >> ./app/upload-key.jks
      - run:
          name: Publish release
          command: ./gradlew publishRelease --no-daemon --stacktrace --console=plain

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
